auth_address = "#fe640b"
auth_bookmarks = "#179299"
auth_password = "#1e66f5"
auth_port = "#04a5e5"
auth_protocol = "#179299"
auth_recents = "#1e66f5"
auth_username = "#ea76cb"
misc_error_dialog = "#d20f39"
misc_info_dialog = "#df8e1d"
misc_input_dialog = "#4c4f69"
misc_keys = "#209fb5"
misc_quit_dialog = "#fe640b"
misc_save_dialog = "#04a5e5"
misc_warn_dialog = "#e64553"
transfer_local_explorer_background = "#eff1f5"
transfer_local_explorer_foreground = "#4c4f69"
transfer_local_explorer_highlighted = "#fe640b"
transfer_log_background = "#eff1f5"
transfer_log_window = "#179299"
transfer_progress_bar_full = "#40a02b"
transfer_progress_bar_partial = "#40a02b"
transfer_remote_explorer_background = "#eff1f5"
transfer_remote_explorer_foreground = "#4c4f69"
transfer_remote_explorer_highlighted = "#1e66f5"
transfer_status_hidden = "#1e66f5"
transfer_status_sorting = "#df8e1d"
transfer_status_sync_browsing = "#179299"
