auth_address = "#fab387"
auth_bookmarks = "#a6e3a1"
auth_password = "#89b4fa"
auth_port = "#89dceb"
auth_protocol = "#a6e3a1"
auth_recents = "#89b4fa"
auth_username = "#f5c2e7"
misc_error_dialog = "#f38ba8"
misc_info_dialog = "#f9e2af"
misc_input_dialog = "#cdd6f4"
misc_keys = "#74c7ec"
misc_quit_dialog = "#fab387"
misc_save_dialog = "#89dceb"
misc_warn_dialog = "#eba0ac"
transfer_local_explorer_background = "#1e1e2e"
transfer_local_explorer_foreground = "#cdd6f4"
transfer_local_explorer_highlighted = "#fab387"
transfer_log_background = "#1e1e2e"
transfer_log_window = "#a6e3a1"
transfer_progress_bar_full = "#a6e3a1"
transfer_progress_bar_partial = "#a6e3a1"
transfer_remote_explorer_background = "#1e1e2e"
transfer_remote_explorer_foreground = "#cdd6f4"
transfer_remote_explorer_highlighted = "#89b4fa"
transfer_status_hidden = "#89b4fa"
transfer_status_sorting = "#f9e2af"
transfer_status_sync_browsing = "#a6e3a1"
