auth_address = "#e5c890"
auth_bookmarks = "#e5c890"
auth_password = "#99d1db"
auth_port = "#81c8be"
auth_protocol = "#e5c890"
auth_recents = "#99d1db"
auth_username = "#ca9ee6"
misc_error_dialog = "#e78284"
misc_info_dialog = "#e5c890"
misc_input_dialog = "#c6d0f5"
misc_keys = "#8caaee"
misc_quit_dialog = "#e5c890"
misc_save_dialog = "#81c8be"
misc_warn_dialog = "#ea999c"
transfer_local_explorer_background = "#303446"
transfer_local_explorer_foreground = "#c6d0f5"
transfer_local_explorer_highlighted = "#e5c890"
transfer_log_background = "#303446"
transfer_log_window = "#e5c890"
transfer_progress_bar_full = "##a6d189"
transfer_progress_bar_partial = "##a6d189"
transfer_remote_explorer_background = "#303446"
transfer_remote_explorer_foreground = "#c6d0f5"
transfer_remote_explorer_highlighted = "#99d1db"
transfer_status_hidden = "#99d1db"
transfer_status_sorting = "#e5c890"
transfer_status_sync_browsing = "#e5c890"
