auth_address = "#f5a97f"
auth_bookmarks = "#a6da95"
auth_password = "#8aadf4"
auth_port = "#8bd5ca"
auth_protocol = "#a6da95"
auth_recents = "#8aadf4"
auth_username = "#f5bde6"
misc_error_dialog = "#ed8796"
misc_info_dialog = "#eed49f"
misc_input_dialog = "#cad3f5"
misc_keys = "#7dc4e4"
misc_quit_dialog = "#f5a97f"
misc_save_dialog = "#8bd5ca"
misc_warn_dialog = "#ee99a0"
transfer_local_explorer_background = "#24273a"
transfer_local_explorer_foreground = "#cad3f5"
transfer_local_explorer_highlighted = "#f5a97f"
transfer_log_background = "#cad3f5"
transfer_log_window = "#a6da95"
transfer_progress_bar_full = "#a6da95"
transfer_progress_bar_partial = "#a6da95"
transfer_remote_explorer_background = "#24273a"
transfer_remote_explorer_foreground = "#cad3f5"
transfer_remote_explorer_highlighted = "#8aadf4"
transfer_status_hidden = "#8aadf4"
transfer_status_sorting = "#eed49f"
transfer_status_sync_browsing = "#a6da95"
